[project]
site_name = "Sephley's Wiki"
site_url = "https://sephley.github.io/wiki/"
docs_dir = "docs"
site_dir = "site"

[project.theme]
palette.primary = "deep purple"
palette.accent = "red"
palette.scheme = "slate"

nav = [
  {"Home" = "index.md"},
  {"Editing" = [
     "editing/index.md",
     "editing/software.md"
  ]},
  {"Streaming" = [
     "streaming/mods.md"
  ]}
]
